name: Upload Python Package

on:
  push:
    tags:
      - 'v*'  # Example: v0.1.0

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi  # must match your PyPI form

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install build tools
        run: |
          python -m pip install --upgrade build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          user: __token__
          password: ${{ secrets.__token__}}
